[tool.poetry]
name = "qatch"
version = "0.1.0"
description = ""
authors = ["spapicchio <simone.papicchio@polito.it>"]
readme = "README.md"
packages = [
    { include = "qatch" },
]

# These packages are mandatory and form the core of this package’s distribution.
[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=1.5.3"
chardet = ">=3.0.2"
xformers = ">=0.0.20"
# A list of all of the optional dependencies to run prediction with QATCH
accelerate = { version = ">=0.21.0", optional = true }
torch = { version = ">=2.0.0", optional = true }
openai = { version = ">=0.27.6", optional = true }
transformers = { version = ">=4.29.0", optional = true }
tqdm = "^4.66.1"

[tool.poetry.extras]
model = ["accelerate", "torch", "openai", "transformers"]

# TEST group
[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
